$schema: "../schema.json"

id: "hidden-site"
name: "Strony nie z tego świata"
flag_hash: "72412ad8387e31782da9131c7557d9b85bcde747bddf25f12a5711bd7fe0c503"

difficulty_estimate: easy
labels:
  - misc

authors:
  - name: "P0m1d00r"
    url: "https://github.com/P0m1d00r"

task_release_phase: morning-day-1

display:
  icon_coordinates:
    #proposed location: Hotel Forum
    x: 19.936133
    y: 50.045043


