services:
  traefik:
    image: docker.io/traefik:v3.7@sha256:6b9cbca6fac42ab0075f5437d8dc1685cfd188626d8d515839ea94f8b6271c42
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=ctf-services-net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.solr.address=:8983"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.http.tls=true"
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - "--entrypoints.metrics.address=:9300"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8983
        published: 8983
        protocol: tcp
        mode: ingress
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /etc/traefik/certs:/etc/traefik/certs:ro
      - /etc/traefik/dynamic:/etc/traefik/dynamic:ro
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - bridge-net
      - ctf-services-net

networks:
  bridge-net:
    external: true
    name: bridge
  ctf-services-net:
    external: true
