$schema: "../schema.json"

id: "smog4shell"
name: "Smog4Shell"
flag_hash: "16a49919dd09a4e54e1a3ddf6697f25a9403fbe9a6b2582684b05427e0d2f8ea"
difficulty_estimate: "medium"
labels:
  - "real_world"
  - "pwn"

task_release_phase: morning-day-2

assets:
  - description: "Fragment logów aplikacji"
    path: "log.txt"

display:
  #proposed location: Elektrociepłownia Kraków
  icon_coordinates:
    x: 20.006666235654688
    y: 50.05332679846385
