$schema: "../schema.json"

id: "smog4shell"
name: "Smog4Shell"
flag_hash: "1d0c1e6e195c267e7076ef67aa1d6b064d7cc86d677a55d6a05b275c69af339c"
difficulty_estimate: "medium"
labels:
  - "real_world"

task_release_phase: main

display:
  # Proposed location: Radio Kraków
  icon_coordinates:
    x: 24
    y: 20
