services:
  smog4shell:
    build: .
    image: smog4shell
    environment:
      SQLITE_DB_PATH: /app/data/smog4shell.sqlite
      SOLR_NETWORK: ctf-services-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sqlite-data:/app/data
    networks:
      - ctf-services-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smog4shell.rule=Host(`smog4shell.hack4krak.pl`)"
      - "traefik.http.services.smog4shell.loadbalancer.server.port=3000"
volumes:
  sqlite-data:

networks:
  ctf-services-net:
    external: true
    name: bridge

