services:
  smog4shell:
    build: .
    image: smog4shell
    environment:
      DATABASE_URL: postgres://ctf:ctf@db:5432/ctf
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ctf-services-net
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.session-snack.rule=Host(`smog4shell.hack4krak.pl`)"
      - "traefik.http.services.session-snack.loadbalancer.server.port=3000"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: ctf
      POSTGRES_DB: ctf
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  ctf-services-net:
    external: true
    name: bridge
  internal:
    internal: true