$schema: "../schema.json"

id: "co-tam-sie-odjaniepawla"
name: "Co tam się odjaniepawla?"
flag_hash: "66d649c300045b7c51a448e5f0419a621db35a11b23757989e66353add5409c0"
difficulty_estimate: "easy"
labels:
  - "games"

task_release_phase: morning-day-1

authors:
  - name: "Goteusz"
    url: "https://github.com/goteusz-maszyk"

display:
  # Centrum Jana Pawła II "Nie lękajcie się!", Łagiewniki
  icon_coordinates:
    x: 19.987222
    y: 50.020278
