services:
  unemployment-is-over-party:
    image: unemployment-is-over-party
    build: .
    networks:
      - ctf-services-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.session-snack.rule=Host(`unemployment-is-over-party.hack4krak.pl`)"
      - "traefik.http.services.session-snack.loadbalancer.server.port=3000"

networks:
  ctf-services-net:
    external: true
    name: bridge