$schema: "../schema.json"

id: "rybulbol"
name: "rybulbol"
flag_hash: "8a53deda6fbb338f2fcc3877994f606637581dc8d3cb8066390fb0b70440c9bc"
difficulty_estimate: "hard"
labels:
  - "games"
  - "reverse engineering"

authors:
  - name: "wojpo"
    url: "https://github.com/wojpo"

task_release_phase: main

assets:
  - description: "Zmodyfikowana gra rybulból"
    path: "rybulbol.zip"

display:
  # wisła
  icon_coordinates:
    x: 19.997955
    y: 50.053684
