# This file defines the participant tags and their types used in the project.
# Participant tags are used for verification of participants during things like registration or serving meals.
# Each tag has a type that categorizes its purpose.

participant-tags:
  - name: "Obecny na wydarzeniu"
    id: "present-on-event"
    description: "Uczestnik jest obecny na wydarzeniu i może wysyłać flagi."
    type: "verified"

  # --- Meals: Day 1 ---
  - name: "Śniadanie dzień 1"
    id: "breakfast-day-1"
    description: "Uczestnik otrzymał śniadanie w pierwszym dniu wydarzenia."
    type: "meal"

  - name: "Obiad dzień 1"
    id: "lunch-day-1"
    description: "Uczestnik otrzymał obiad w pierwszym dniu wydarzenia."
    type: "meal"

  - name: "Kolacja dzień 1"
    id: "dinner-day-1"
    description: "Uczestnik otrzymał kolację w pierwszym dniu wydarzenia."
    type: "meal"

  # --- Meals: Day 2 ---
  - name: "Śniadanie dzień 2"
    id: "breakfast-day-2"
    description: "Uczestnik otrzymał śniadanie w drugim dniu wydarzenia."
    type: "meal"

  - name: "Obiad dzień 2"
    id: "lunch-day-2"
    description: "Uczestnik otrzymał obiad w drugim dniu wydarzenia."
    type: "meal"
