$schema: "../schema.json"

id: "zakrzowek-fast-pass"
name: "Zakrzowek Fast Pass"
flag_hash: "546fd91d96b3c40ebbe188760a697e932776b9c973056c705f30eb41bcddea75"
difficulty_estimate: "rookie"
labels:
  - "web"
  - "misc"

task_release_phase: start

display:
  # Zakrzowek swimming area
  icon_coordinates:
    x: 19.9165
    y: 50.0367
