services:
  real-world-server-1:
    build: ./server-1
    ports:
      - "80:80"
      - "2222:22"
    networks:
      - public-net
      - internal-net

networks:
  public-net:
    driver: bridge

  internal-net:
    driver: bridge