services:
  real-world-server-1:
    build: ./server-1
    networks:
      ctf-services-net:
      internal-net:
        ipv4_address: 10.10.10.1

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server1.rule=Host(`server1.docker.localhost`)"
      - "traefik.http.services.server1.loadbalancer.server.port=80"
      - "traefik.tcp.routers.server1-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.server1-ssh.entrypoints=ssh"
      - "traefik.tcp.services.server1-ssh.loadbalancer.server.port=22"

  real-world-server-2:
    build: ./server-2
    networks:
      internal-net:
        ipv4_address: 10.10.10.2

networks:
  ctf-services-net:
    external: true

  internal-net:
    internal: true
    ipam:
      config:
        - subnet: 10.10.10.0/24