$schema: "../schema.json"

id: "900728"
name: "900728"
flag_hash: "8ea6236b80ad02d9f2d7dcea4d77fcdb6bb8650585b79f30f6c32e35e5c01d25"
difficulty_estimate: "easy"
labels:
  - "misc"

task_release_phase: morning-day-1

assets:
  - description: "Plik audio z zadaniem"
    path: "900728.wav"

display:
  # ICE Kraków Congress Centre
  icon_coordinates:
    x: 19.929167
    y: 50.046944