$schema: "../schema.json"

id: "mocak"
name: "MOCAK"
flag_hash: "6967805265cb0c0d2955d9d1cc31a3e97097a597daff3ddd0c62f739e284e672"
difficulty_estimate: "medium"
labels:
  - "misc"

task_release_phase: start

assets:
  - description: "Zdjęcie z naszej wycieczki w MOCAKu"
    path: "mocak.png"

display:
  # MOCAK - Muzeum Sztuki Współczesnej w Krakowie
  icon_coordinates:
    x: 19.961348
    y: 50.047866
